### ISSUE TITLE
java.io.FileNotFoundException when calling (load-plugins)

### ISSUE THREAD

**Issue by CVTJNII** [avishai-ish-shalom/riemann-flapjack-output#4]
I have built the riemann_flapjack_output in a clean environment and can start Riemann with the jar in the classpath.  However, when I call (load-plugins) in my config I get the following exception:

```
INFO [2015-09-24 20:26:42,560] SIGHUP handler - riemann.bin - Caught SIGHUP, reloading
INFO [2015-09-24 20:26:42,561] SIGHUP handler - riemann.pubsub - Sweeping transient subscriptions.
INFO [2015-09-24 20:26:42,575] SIGHUP handler - riemann.plugin - walking classpath to find plugins
INFO [2015-09-24 20:26:42,608] SIGHUP handler - riemann.plugin - loading plugin: flapjack
ERROR [2015-09-24 20:26:42,611] SIGHUP handler - riemann.bin - Couldn't reload:
java.io.FileNotFoundException: Could not locate taoensso/carmine__init.class or taoensso/carmine.clj on classpath: , compiling:(riemann_flapjack_output/core.clj:1:1)
        at clojure.lang.Compiler.load(Compiler.java:7142)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.loadResourceScript(RT.java:361)
        at clojure.lang.RT.load(RT.java:440)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at riemann.plugin$load_from_meta.invoke(plugin.clj:43)
        at riemann.plugin$load_from_resource.invoke(plugin.clj:53)
        at riemann.plugin$load_plugins.invoke(plugin.clj:64)
        at riemann.plugin$load_plugins.invoke(plugin.clj:66)
        at riemann.config$eval6961.invoke(alerts.config:25)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.lang.RT$3.invoke(RT.java:318)
        at riemann.config$include.invoke(config.clj:408)
        at clojure.core$map$fn__4245.invoke(core.clj:2559)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.LazySeq.next(LazySeq.java:81)
        at clojure.lang.RT.next(RT.java:598)
        at clojure.core$next.invoke(core.clj:64)
        at clojure.core$dorun.invoke(core.clj:2856)
        at riemann.config$include.invoke(config.clj:404)
        at riemann.config$eval6908.invoke(riemann.config:7)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.lang.RT$3.invoke(RT.java:318)
        at riemann.config$include.invoke(config.clj:408)
        at riemann.bin$reload_BANG_.invoke(bin.clj:27)
        at riemann.bin$handle_signals$fn__11886.invoke(bin.clj:43)
        at riemann.bin.proxy$java.lang.Object$SignalHandler$d8c00ec7.handle(Unknown Source)
        at sun.misc.Signal$1.run(Signal.java:212)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: Could not locate taoensso/carmine__init.class or taoensso/carmine.clj on classpath:
        at clojure.lang.RT.load(RT.java:443)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:512)
        at riemann_flapjack_output.core$eval6965$loading__4958__auto____6966.invoke(core.clj:1)
        at riemann_flapjack_output.core$eval6965.invoke(core.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6692)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        ... 47 more
```

Is this dependency supposed to be included in the riemann-flapjack-output jar?  I'm building off eaefacbac79a432d895ed218ec194c419f026002 and am running riemann-0.2.10.

**Comment by CVTJNII** [comment]
User error, I wasn't using the standalone jar.
